### PR TITLE
[JENKINS-40808] Inception

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-40808](https://issues.jenkins-ci.org/browse/JENKINS-40808)

If accepted, also requires [HOSTING-254](https://issues.jenkins-ci.org/browse/HOSTING-254).

@reviewbybees

### CODE REVIEW

**Comment by scoheb** [comment]
FYI...using this on another project. Working great!

**Comment by scoheb** [comment]
Any update on getting this made available?

**Comment by jglick** [comment]
> Any update on getting this made available?

I am awaiting review especially from @olivergondza.

> Many files are missing a copyright header.

Only ones which were moved from `acceptance-test-harness` I hope, but I will check if a license declaration is needed for the new stuff as well.

**Comment by olivergondza** [comment]
Lets do this. :+1:

**Pull request merged**
